# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30)),
                ('inbound_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('redirect_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('welcome_message', models.FileField(upload_to='audio/')),
                ('is_active', models.FileField(default=False, upload_to='')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
