# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20170712_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='inbound_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='redirect_number',
            field=models.CharField(max_length=30),
        ),
    ]
